module.exports = {
  characters: [
    {
      name: "Ross Geller",
      occupation: "Paleontologist",
      age: 32,
      relationship_status: "Divorced",
      friends: [
        "Rachel Green",
        "Monica Geller",
        "Chandler Bing",
        "Joey Tribbiani",
        "Phoebe Buffay",
      ],
      image: "https://i.ibb.co/R3qYz26/ross.jpg",
      gender: "Male",
      description:
        "Ross Geller is a highly intelligent paleontologist who is often known for his nerdy and awkward demeanor. He is passionate about dinosaurs and spends most of his time working at the museum.",
      favourite_dialogue: "We were on a break!",
    },
    {
      name: "Rachel Green",
      occupation: "Fashion Executive",
      age: 30,
      relationship_status: "In a relationship",
      friends: [
        "Monica Geller",
        "Chandler Bing",
        "Joey Tribbiani",
        "Phoebe Buffay",
      ],
      image: "https://i.ibb.co/Qk4kGL9/rachel.jpg",
      gender: "Female",
      description:
        "Rachel Green is a fashionable and independent woman who starts off as a spoiled daddy's girl. Throughout the series, she evolves into a strong and determined career woman.",
      favourite_dialogue: "I got off the plane.",
    },
    {
      name: "Monica Geller",
      occupation: "Chef",
      age: 28,
      relationship_status: "Married",
      friends: [
        "Rachel Green",
        "Ross Geller",
        "Chandler Bing",
        "Joey Tribbiani",
        "Phoebe Buffay",
      ],
      image: "https://i.ibb.co/C1Q9njv/monica.jpg",
      gender: "Female",
      description:
        "Monica Geller is a perfectionist and talented chef with a strong competitive streak. She is known for her cleanliness and organization skills, and she often takes on the role of the responsible friend in the group.",
      favourite_dialogue: "I know! I'll become a chef!",
    },
    {
      name: "Chandler Bing",
      occupation: "Advertising Executive",
      age: 31,
      relationship_status: "Married",
      friends: [
        "Rachel Green",
        "Monica Geller",
        "Ross Geller",
        "Joey Tribbiani",
        "Phoebe Buffay",
      ],
      image: "https://i.ibb.co/CnwswhX/chandler.jpg",
      gender: "Male",
      description:
        "Chandler Bing is known for his sarcastic wit and sense of humor. He often uses humor as a defense mechanism and struggles with commitment and emotional vulnerability.",
      favourite_dialogue: "Could I be wearing any more clothes?",
    },
    {
      name: "Joey Tribbiani",
      occupation: "Actor",
      age: 28,
      relationship_status: "Single",
      friends: [
        "Rachel Green",
        "Monica Geller",
        "Chandler Bing",
        "Ross Geller",
        "Phoebe Buffay",
      ],
      image: "https://i.ibb.co/HgBddV6/joey.webp",
      gender: "Male",
      description:
        "Joey Tribbiani is an aspiring actor with a charming and lovable personality. He is known for his womanizing ways, love for food, and iconic catchphrase, 'How you doin'?'",
      favourite_dialogue: "Joey doesn't share food!",
    },
    {
      name: "Phoebe Buffay",
      occupation: "Massage Therapist",
      age: 33,
      relationship_status: "Married",
      friends: [
        "Rachel Green",
        "Monica Geller",
        "Chandler Bing",
        "Ross Geller",
        "Joey Tribbiani",
      ],
      image: "https://i.ibb.co/VSvjMyT/phoebe.webp",
      gender: "Female",
      description:
        "Phoebe Buffay is a free-spirited and eccentric musician who often brings a unique perspective to the group. She has a quirky sense of humor and a love for performing her original songs.",
      favourite_dialogue: "Smelly Cat, Smelly Cat, what are they feeding you?",
    },
  ],
  extras: [
    {
      name: "Janice Hosenstein",
      occupation: "Unknown",
      age: 35,
      relationship_status: "Divorced",
      friends: ["Chandler Bing"],
      image: "https://i.ibb.co/LPkvYsx/janice.jpg",
      gender: "Female",
      description:
        "Janice Hosenstein is a loud and overly dramatic woman who has an on-again, off-again relationship with Chandler Bing. Her distinctive voice and catchphrase 'Oh. My. God.' make her a memorable character.",
      favourite_dialogue: "Oh. My. God!",
    },
    {
      name: "Gunther",
      occupation: "Barista",
      age: 28,
      relationship_status: "Single",
      friends: ["Rachel Green"],
      image: "https://i.ibb.co/HDsWJJk/gunther.jpg",
      gender: "Male",
      description:
        "Gunther is a quiet and often unnoticed barista at Central Perk, the coffee shop where the friends frequently hang out. He has an unrequited love for Rachel and is known for his bleached blonde hair.",
      favourite_dialogue: "I love you. (to Rachel)",
    },
    {
      name: "Mike Hannigan",
      occupation: "Unknown",
      age: 35,
      relationship_status: "Married",
      friends: ["Phoebe Buffay"],
      image: "https://i.ibb.co/wcDtfgC/mike.jpg",
      gender: "Male",
      description:
        "Mike Hannigan is a kind-hearted and supportive man who becomes Phoebe Buffay's husband. He is initially hesitant about marriage but eventually realizes his love for Phoebe.",
      favourite_dialogue: "Phoebe, you're my wife now.",
    },
    {
      name: "Estelle Leonard",
      occupation: "Agent",
      age: 52,
      relationship_status: "Single",
      friends: ["Joey Tribbiani"],
      image: "https://i.ibb.co/drq1HWV/estelle.jpg",
      gender: "Female",
      description:
        "Estelle Leonard is Joey Tribbiani's tough-talking and somewhat unprofessional talent agent. She often gets Joey auditions for questionable roles and is known for her brash personality.",
      favourite_dialogue: "Joey, baby! How you doin'?",
    },
    {
      name: "Mr. Heckles",
      occupation: "Unknown",
      age: 65,
      relationship_status: "Single",
      friends: [],
      image: "https://i.ibb.co/HF0MmkJ/heckles.webp",
      gender: "Male",
      description:
        "Mr. Heckles is the eccentric and grumpy neighbor who lives below Monica and Rachel's apartment. He frequently complains about the noise from their apartment and is known for his peculiar behavior.",
      favourite_dialogue: "You're disturbing my oboe practice!",
    },
    {
      name: "Emily Waltham",
      occupation: "Unknown",
      age: 28,
      relationship_status: "Married",
      friends: [],
      image: "https://i.ibb.co/S6rypQb/emily.jpg",
      gender: "Female",
      description:
        "Emily Waltham is a British woman whom Ross dates and eventually marries. Their relationship becomes complicated when Ross accidentally says Rachel's name during their wedding vows.",
      favourite_dialogue:
        "I can't marry someone who's in love with someone else.",
    },
    {
      name: "Richard Burke",
      occupation: "Ophthalmologist",
      age: 45,
      relationship_status: "Divorced",
      friends: [],
      image: "https://i.ibb.co/r3m5rBW/richard.jpg",
      gender: "Male",
      description:
        "Richard Burke is an older man who becomes involved in a romantic relationship with Monica. He is a successful ophthalmologist and shares a love for fine dining and travel with Monica.",
      favourite_dialogue:
        "I'm sorry, but I don't want to be just a good story.",
    },
    {
      name: "Judy Geller",
      occupation: "Unknown",
      age: 58,
      relationship_status: "Married",
      friends: [],
      image: "https://i.ibb.co/9ggwnHN/judy.jpg",
      gender: "Female",
      description:
        "Judy Geller is Ross and Monica's mother. She is portrayed as critical and overbearing, often making sarcastic remarks. She is married to Jack Geller and is known for her competitive nature.",
      favourite_dialogue:
        "I'm not speaking to you until you apologize to your sister!",
    },
    {
      name: "Ursula Buffay",
      occupation: "Waitress",
      age: 33,
      relationship_status: "Single",
      friends: [],
      image: "https://i.ibb.co/cJz5t8S/ursula.jpg",
      gender: "Female",
      description:
        "Ursula Buffay is Phoebe Buffay's identical twin sister. She is often portrayed as selfish and manipulative. She works as a waitress and is known for her aloof personality.",
      favourite_dialogue: "I'm busy. Can I ignore you some other time?",
    },
    {
      name: "Carol Willick",
      occupation: "Unknown",
      age: 33,
      relationship_status: "Married",
      friends: [],
      image: "https://i.ibb.co/Cb9sQdG/carol.jpg",
      gender: "Female",
      description:
        "Carol Willick is Ross's ex-wife and the mother of his son, Ben. She later marries Susan Bunch and co-parents Ben with Ross. Carol's relationship with Ross is a recurring theme throughout the series.",
      favourite_dialogue:
        "I don't want Ben to grow up and not know who his real mother is.",
    },
  ],
};
